# Generated by Django 6.0.6 on 2026-07-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyorder',
            unique_together=set(),
        ),
    ]
